#!/usr/bin/env python3
"""
Common data loading functions for RCCL benchmark analysis.

This module provides standardized functions for loading and parsing
benchmark output data, timing data, kernel traces, and timestamps.

All functions return pandas DataFrames with consistent schemas
to ensure interoperability across analysis scripts.
"""

import os
import sys
import re
import glob
import pandas as pd
import numpy as np
from pathlib import Path


def find_benchmark_name(run_dir):
    """
    Extract benchmark name from run directory path.
    
    Args:
        run_dir: Path to run directory (e.g., 'run_all_reduce_20251110_135024')
    
    Returns:
        str: Benchmark name (e.g., 'all_reduce')
    """
    dir_name = os.path.basename(run_dir.rstrip('/'))
    
    # Expected format: run_{benchmark_name}_{YYYYMMDD_HHMMSS}
    if not dir_name.startswith('run_'):
        raise ValueError(f"Invalid run directory format: {dir_name}")
    
    # Remove 'run_' prefix and timestamp suffix
    timestamp_pattern = r'_\d{8}_\d{6}$'
    match = re.search(timestamp_pattern, dir_name)
    
    if not match:
        raise ValueError(f"Cannot find timestamp pattern in directory: {dir_name}")
    
    timestamp_start = match.start()
    benchmark_name = dir_name[4:timestamp_start]  # Skip 'run_' prefix
    
    return benchmark_name


def load_benchmark_output(run_dir, benchmark_name=None):
    """
    Load benchmark output CSV file.
    
    The benchmark CSV is generated with -x and -Z csv flags and contains
    per-size timing and bandwidth measurements for both in-place and
    out-of-place operations.
    
    Args:
        run_dir: Path to run directory
        benchmark_name: Optional benchmark name (auto-detected if None)
    
    Returns:
        pd.DataFrame with columns:
            - numCycle (int): Benchmark cycle number
            - collective (str): Collective operation name
            - ranks (int): Number of ranks
            - rankspernode (int): Ranks per node
            - gpusperrank (int): GPUs per rank
            - size_bytes (int): Message size in bytes
            - data_type (str): Data type (e.g., 'float')
            - redop (str): Reduction operation (e.g., 'sum')
            - inplace (int): 0 for out-of-place, 1 for in-place
            - wall_time_us (float): Wall clock time in microseconds
            - algbw_gbs (float): Algorithm bandwidth in GB/s (G=10^9)
            - busbw_gbs (float): Bus bandwidth in GB/s (G=10^9)
            - busbw_factor (float): Bus bandwidth factor (busbw / algbw)
            - errors (int): Number of errors
        
        Returns empty DataFrame if file not found.
    """
    if benchmark_name is None:
        benchmark_name = find_benchmark_name(run_dir)
    
    csv_file = os.path.join(run_dir, f'{benchmark_name}_benchmark_output.csv')
    
    if not os.path.exists(csv_file):
        print(f"Warning: Benchmark CSV not found: {csv_file}")
        return pd.DataFrame()
    
    # Read CSV with standard column names
    df = pd.read_csv(csv_file)
    
    # Standardize column names for consistency across scripts
    column_mapping = {
        'size': 'size_bytes',
        'type': 'data_type',
        'time': 'wall_time_us',
        'algbw': 'algbw_gbs',
        'busbw': 'busbw_gbs',
        'busbwfactor': 'busbw_factor',
        '#wrong': 'errors'
    }
    
    df = df.rename(columns=column_mapping)
    
    # Ensure consistent types
    df['size_bytes'] = df['size_bytes'].astype(int)
    df['inplace'] = df['inplace'].astype(int)
    df['wall_time_us'] = df['wall_time_us'].astype(float)
    df['algbw_gbs'] = df['algbw_gbs'].astype(float)
    df['busbw_gbs'] = df['busbw_gbs'].astype(float)
    df['busbw_factor'] = df['busbw_factor'].astype(float)
    df['errors'] = df['errors'].astype(int)
    
    return df


def load_timing_data(run_dir):
    """
    Load all rank timing CSVs into a single DataFrame.
    
    These CSVs are generated by the benchmark with per-kernel timing
    measurements and IQR filtering flags.
    
    Args:
        run_dir: Path to run directory
    
    Returns:
        pd.DataFrame with columns:
            - rank (int): MPI rank
            - size_bytes (int): Message size
            - inplace (int): 0 for out-of-place, 1 for in-place
            - iteration (int): Iteration number
            - kernel_time_us (float): Kernel execution time
            - IQR_filtered (bool): Whether included after IQR filtering
    """
    csv_files = sorted(glob.glob(os.path.join(run_dir, 'all_rank*.csv')))
    
    if not csv_files:
        print(f"Warning: No timing CSV files found in {run_dir}")
        return pd.DataFrame()
    
    dfs = []
    for csv_file in csv_files:
        # Extract rank from filename (e.g., all_rank0.csv -> rank 0)
        filename = os.path.basename(csv_file)
        match = re.search(r'all_rank(\d+)\.csv', filename)
        if not match:
            continue
        
        rank = int(match.group(1))
        df = pd.read_csv(csv_file)
        df['rank'] = rank
        dfs.append(df)
    
    if not dfs:
        return pd.DataFrame()
    
    combined = pd.concat(dfs, ignore_index=True)
    
    # Standardize column names
    if 'Size (bytes)' in combined.columns:
        combined = combined.rename(columns={'Size (bytes)': 'size_bytes'})
    if 'In-place' in combined.columns:
        combined = combined.rename(columns={'In-place': 'inplace'})
    if 'Iteration' in combined.columns:
        combined = combined.rename(columns={'Iteration': 'iteration'})
    if 'Kernel Time (us)' in combined.columns:
        combined = combined.rename(columns={'Kernel Time (us)': 'kernel_time_us'})
    if 'IQR Filtered' in combined.columns:
        combined = combined.rename(columns={'IQR Filtered': 'IQR_filtered'})
    
    return combined


def load_bic_segmentation(run_dir, benchmark_name=None):
    """
    Load BIC segmentation results.
    
    Args:
        run_dir: Path to run directory
        benchmark_name: Optional benchmark name (auto-detected if None)
    
    Returns:
        dict: Segmentation data with keys:
            - 'benchmark': Benchmark name
            - 'n_segments': Number of segments
            - 'segments': List of segment dicts with:
                - 'segment_id': int
                - 'size_range_bytes': (min, max) tuple
                - 'formula': str (e.g., "y = 2.3 + 0.45*log2(x)")
                - 'r_squared': float
                - 'bic': float
        
        Returns None if file not found.
    """
    if benchmark_name is None:
        benchmark_name = find_benchmark_name(run_dir)
    
    import json
    seg_file = os.path.join(run_dir, f'{benchmark_name}_bic_segmentation.json')
    
    if not os.path.exists(seg_file):
        print(f"Warning: BIC segmentation not found: {seg_file}")
        return None
    
    with open(seg_file, 'r') as f:
        return json.load(f)


def load_rank_pid_mapping(run_dir):
    """
    Load rank-to-PID mapping from run metadata.
    
    Args:
        run_dir: Path to run directory
    
    Returns:
        dict: Mapping from rank (int) to PID (int)
        Returns empty dict if metadata not found.
    """
    import json
    metadata_file = os.path.join(run_dir, 'run_metadata.json')
    
    if not os.path.exists(metadata_file):
        print(f"Warning: Metadata file not found: {metadata_file}")
        return {}
    
    with open(metadata_file, 'r') as f:
        metadata = json.load(f)
    
    rank_pid_map = metadata.get('rank_pid_mapping', {})
    
    # Convert string keys to integers
    return {int(k): int(v) for k, v in rank_pid_map.items()}


def load_kernel_traces(run_dir, rank_pid_map=None):
    """
    Load all ROCProfiler kernel traces into a single DataFrame.
    
    This function loads kernel dispatch events from ROCProfiler CSV files
    and optionally augments them with rank information.
    
    Args:
        run_dir: Path to run directory
        rank_pid_map: Optional dict mapping rank -> PID (auto-loaded if None)
    
    Returns:
        pd.DataFrame with columns:
            - rank (int): MPI rank (if rank_pid_map provided)
            - pid (int): Process ID
            - kernel_name (str): Kernel function name
            - begin_ns (int): Kernel start time in nanoseconds
            - end_ns (int): Kernel end time in nanoseconds
            - duration_ns (int): Kernel duration in nanoseconds
            - is_nccl (bool): Whether kernel is an NCCL kernel
    """
    if rank_pid_map is None:
        rank_pid_map = load_rank_pid_mapping(run_dir)
    
    # Find ROCProfiler kernel trace files
    hostname = os.uname().nodename
    rocp_dir = os.path.join(run_dir, 'rocp', hostname)
    
    if not os.path.exists(rocp_dir):
        print(f"Warning: ROCProfiler directory not found: {rocp_dir}")
        return pd.DataFrame()
    
    trace_files = glob.glob(os.path.join(rocp_dir, '*_kernel_trace.csv'))
    
    if not trace_files:
        print(f"Warning: No kernel trace files found in {rocp_dir}")
        return pd.DataFrame()
    
    # Create reverse mapping: PID -> rank
    pid_rank_map = {v: k for k, v in rank_pid_map.items()}
    
    dfs = []
    for trace_file in trace_files:
        # Extract PID from filename
        match = re.search(r'(\d+)_kernel_trace\.csv', os.path.basename(trace_file))
        if not match:
            continue
        
        pid = int(match.group(1))
        
        # Read kernel trace CSV
        df = pd.read_csv(trace_file)
        
        # Filter to KERNEL_DISPATCH events only
        if 'Type' in df.columns:
            df = df[df['Type'] == 'KERNEL_DISPATCH'].copy()
        
        # Standardize column names
        if 'Name' in df.columns:
            df = df.rename(columns={'Name': 'kernel_name'})
        if 'BeginNs' in df.columns:
            df = df.rename(columns={'BeginNs': 'begin_ns'})
        if 'EndNs' in df.columns:
            df = df.rename(columns={'EndNs': 'end_ns'})
        if 'DurationNs' in df.columns:
            df = df.rename(columns={'DurationNs': 'duration_ns'})
        
        # Add PID and rank
        df['pid'] = pid
        if pid in pid_rank_map:
            df['rank'] = pid_rank_map[pid]
        
        # Mark NCCL kernels
        df['is_nccl'] = df['kernel_name'].str.contains('ncclKernel', case=False, na=False)
        
        dfs.append(df)
    
    if not dfs:
        return pd.DataFrame()
    
    combined = pd.concat(dfs, ignore_index=True)
    
    # Ensure consistent column order
    columns = ['rank', 'pid', 'kernel_name', 'begin_ns', 'end_ns', 'duration_ns', 'is_nccl']
    available_columns = [col for col in columns if col in combined.columns]
    
    return combined[available_columns]


def load_timestamp_ranges(run_dir, ranks=None):
    """
    Load benchmark timing ranges from timestamp files.
    
    These files contain Tstart/Tend markers that bracket the actual
    timed kernel launches for each size and operation mode.
    
    Args:
        run_dir: Path to run directory
        ranks: Optional list of ranks to load (loads all if None)
    
    Returns:
        pd.DataFrame with columns:
            - rank (int): MPI rank
            - size_bytes (int): Message size
            - operation_mode (str): 'oop' or 'inp'
            - start_ns (int): Range start time in nanoseconds
            - end_ns (int): Range end time in nanoseconds
            - duration_ns (int): Range duration in nanoseconds
            - config (str): Configuration string
    """
    if ranks is None:
        # Auto-detect ranks from timestamp files
        timestamp_files = glob.glob(os.path.join(run_dir, 'rank_*_timestamps.txt'))
        ranks = []
        for f in timestamp_files:
            match = re.search(r'rank_(\d+)_timestamps\.txt', os.path.basename(f))
            if match:
                ranks.append(int(match.group(1)))
        ranks = sorted(ranks)
    
    if not ranks:
        print(f"Warning: No timestamp files found in {run_dir}")
        return pd.DataFrame()
    
    all_ranges = []
    
    for rank in ranks:
        timestamp_file = os.path.join(run_dir, f'rank_{rank}_timestamps.txt')
        
        if not os.path.exists(timestamp_file):
            continue
        
        with open(timestamp_file, 'r') as f:
            lines = f.readlines()
        
        # Parse timestamp events
        events = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            
            # Format: Tstart/Tend timestamp_ns size_bytes config_string
            parts = line.split(maxsplit=3)
            if len(parts) < 3:
                continue
            
            event_type = parts[0]  # Tstart or Tend
            timestamp_ns = int(parts[1])
            size_bytes = int(parts[2])
            config = parts[3] if len(parts) > 3 else ""
            
            events.append({
                'event_type': event_type,
                'timestamp_ns': timestamp_ns,
                'size_bytes': size_bytes,
                'config': config
            })
        
        # Pair Tstart/Tend events into ranges
        i = 0
        while i < len(events) - 1:
            if events[i]['event_type'] == 'Tstart' and events[i+1]['event_type'] == 'Tend':
                # Extract operation mode from config
                config = events[i]['config']
                if '_inp_' in config.lower():
                    op_mode = 'inp'
                elif '_oop_' in config.lower():
                    op_mode = 'oop'
                else:
                    op_mode = 'unknown'
                
                start_ns = events[i]['timestamp_ns']
                end_ns = events[i+1]['timestamp_ns']
                
                all_ranges.append({
                    'rank': rank,
                    'size_bytes': events[i]['size_bytes'],
                    'operation_mode': op_mode,
                    'start_ns': start_ns,
                    'end_ns': end_ns,
                    'duration_ns': end_ns - start_ns,
                    'config': config
                })
                
                i += 2
            else:
                i += 1
    
    return pd.DataFrame(all_ranges)


def filter_kernels_by_size_range(df_kernels, df_ranges, min_size=None, max_size=None):
    """
    Filter kernel traces to only those within specified size ranges and timestamp bounds.
    
    Args:
        df_kernels: DataFrame from load_kernel_traces()
        df_ranges: DataFrame from load_timestamp_ranges()
        min_size: Optional minimum message size (inclusive)
        max_size: Optional maximum message size (inclusive)
    
    Returns:
        pd.DataFrame: Filtered kernels augmented with size_bytes and operation_mode
    """
    if df_kernels.empty or df_ranges.empty:
        return pd.DataFrame()
    
    # Filter ranges by size
    df_ranges_filtered = df_ranges.copy()
    if min_size is not None:
        df_ranges_filtered = df_ranges_filtered[df_ranges_filtered['size_bytes'] >= min_size]
    if max_size is not None:
        df_ranges_filtered = df_ranges_filtered[df_ranges_filtered['size_bytes'] <= max_size]
    
    if df_ranges_filtered.empty:
        return pd.DataFrame()
    
    # Filter to NCCL kernels only
    df_kernels_nccl = df_kernels[df_kernels['is_nccl']].copy()
    
    if df_kernels_nccl.empty:
        return pd.DataFrame()
    
    # Perform interval join: find kernels within each timestamp range
    matched_kernels = []
    
    for _, rng in df_ranges_filtered.iterrows():
        # Find kernels for this rank within this time range
        mask = (
            (df_kernels_nccl['rank'] == rng['rank']) &
            (df_kernels_nccl['begin_ns'] >= rng['start_ns']) &
            (df_kernels_nccl['end_ns'] <= rng['end_ns'])
        )
        
        kernels_in_range = df_kernels_nccl[mask].copy()
        
        if not kernels_in_range.empty:
            # Augment with range information
            kernels_in_range['size_bytes'] = rng['size_bytes']
            kernels_in_range['operation_mode'] = rng['operation_mode']
            kernels_in_range['range_start_ns'] = rng['start_ns']
            kernels_in_range['range_end_ns'] = rng['end_ns']
            
            matched_kernels.append(kernels_in_range)
    
    if not matched_kernels:
        return pd.DataFrame()
    
    return pd.concat(matched_kernels, ignore_index=True)


# Bandwidth calculation functions

def get_bus_bandwidth_factor(collective_name, nranks):
    """
    Get the bus bandwidth factor for a collective operation.
    
    This replicates the logic from the C++ benchmark code and is used
    as a fallback when calculating bus bandwidth from kernel timings
    (where the factor is not pre-computed).
    
    For wall clock times, prefer using busbw_factor from the CSV
    (generated by the benchmark itself).
    
    Args:
        collective_name: Name of collective (e.g., 'all_reduce', 'reduce_scatter')
        nranks: Number of ranks
    
    Returns:
        float: Factor to multiply algorithm bandwidth by to get bus bandwidth
    """
    collective_name = collective_name.lower()
    
    if collective_name in ['all_reduce', 'allreduce']:
        # Ring algorithm: 2 * (N-1) / N
        return 2.0 * (nranks - 1) / nranks
    
    elif collective_name in ['reduce_scatter', 'reducescatter']:
        # (N-1) / N
        return (nranks - 1) / nranks
    
    elif collective_name in ['all_gather', 'allgather']:
        # (N-1) / N
        return (nranks - 1) / nranks
    
    elif collective_name in ['reduce', 'broadcast']:
        # 1.0 (no amplification)
        return 1.0
    
    elif collective_name in ['alltoall', 'alltoallv']:
        # (N-1) / N
        return (nranks - 1) / nranks
    
    elif collective_name in ['sendrecv', 'send', 'recv']:
        # 1.0
        return 1.0
    
    else:
        # Default: assume no amplification
        print(f"Warning: Unknown collective '{collective_name}', using factor=1.0")
        return 1.0


def calculate_algorithm_bandwidth(size_bytes, time_us):
    """
    Calculate algorithm bandwidth.
    
    Args:
        size_bytes: Message size in bytes (can be scalar or array)
        time_us: Time in microseconds (can be scalar or array)
    
    Returns:
        float or np.ndarray: Algorithm bandwidth in GB/s (G=10^9)
    """
    # GB/s = bytes / microseconds / 1000
    # Because: bytes/us * (10^6 us/s) / (10^9 bytes/GB) = bytes/us / 1000
    return size_bytes / time_us / 1000.0


def calculate_bus_bandwidth(size_bytes, time_us, collective_name, nranks):
    """
    Calculate bus bandwidth (accounts for network traffic amplification).
    
    This matches the benchmark's busbw calculation.
    
    Args:
        size_bytes: Message size in bytes (can be scalar or array)
        time_us: Time in microseconds (can be scalar or array)
        collective_name: Name of collective operation
        nranks: Number of ranks
    
    Returns:
        float or np.ndarray: Bus bandwidth in GB/s (G=10^9)
    """
    algbw = calculate_algorithm_bandwidth(size_bytes, time_us)
    factor = get_bus_bandwidth_factor(collective_name, nranks)
    return algbw * factor


# Convenience functions for backward compatibility

def parse_benchmark_output(output_file):
    """
    Legacy function for backward compatibility.
    
    Prefer load_benchmark_output(run_dir) for new code.
    """
    run_dir = os.path.dirname(output_file)
    return load_benchmark_output(run_dir)

