#!/usr/bin/env python3
"""
Regenerate run_metadata.json files for existing benchmark run directories.

This script scans all run directories and creates/updates run_metadata.json
files based on the directory name and existing files.
"""

import os
import sys
import json
import socket
import glob
import re
from datetime import datetime
from pathlib import Path


def extract_metadata_from_dirname(dirname):
    """
    Extract benchmark name and timestamp from directory name.
    
    Expected format: run_{benchmark}_{YYYYMMDD_HHMMSS}
    """
    match = re.match(r'run_([a-z_]+)_(\d{8})_(\d{6})$', dirname)
    if not match:
        return None
    
    benchmark = match.group(1)
    date_str = match.group(2)
    time_str = match.group(3)
    
    # Convert to ISO format timestamp
    timestamp_str = f"{date_str[:4]}-{date_str[4:6]}-{date_str[6:8]}T{time_str[:2]}:{time_str[2:4]}:{time_str[4:6]}"
    
    return {
        'benchmark': benchmark,
        'timestamp': timestamp_str
    }


def infer_run_parameters(run_dir, benchmark):
    """
    Infer run parameters from existing files in the directory.
    """
    params = {}
    
    # Count rank files
    rank_files = glob.glob(os.path.join(run_dir, 'all_rank*.csv'))
    params['ranks'] = len(rank_files)
    
    # Try to read rank_pid_mapping
    rank_pid_file = os.path.join(run_dir, 'rank_pid_mapping.json')
    if os.path.exists(rank_pid_file):
        try:
            with open(rank_pid_file, 'r') as f:
                mapping = json.load(f)
                params['ranks'] = len(mapping)
        except:
            pass
    
    # Try to extract size range from benchmark output
    output_file = os.path.join(run_dir, f'{benchmark}_benchmark_output.txt')
    if os.path.exists(output_file):
        try:
            with open(output_file, 'r') as f:
                content = f.read()
                
                # Look for the header line with minBytes and maxBytes
                match = re.search(r'minBytes\s+(\d+)\s+maxBytes\s+(\d+)', content)
                if match:
                    params['min_size_bytes'] = int(match.group(1))
                    params['max_size_bytes'] = int(match.group(2))
                
                # Look for iterations (not warmup iters)
                # Pattern: "warmup iters: 5 iters: 100"
                match = re.search(r'warmup iters:\s+\d+\s+iters:\s+(\d+)', content)
                if match:
                    params['iterations'] = int(match.group(1))
                else:
                    # Fallback to any "iters:" that's not "warmup iters:"
                    match = re.search(r'(?<!warmup )iters:\s+(\d+)', content)
                    if match:
                        params['iterations'] = int(match.group(1))
                
                # Look for warmup
                match = re.search(r'warmup\s+iters:\s+(\d+)', content)
                if match:
                    params['warmup_iterations'] = int(match.group(1))
        except:
            pass
    
    # Set defaults if not found
    if 'min_size_bytes' not in params:
        params['min_size_bytes'] = 8  # Default
    if 'max_size_bytes' not in params:
        params['max_size_bytes'] = 1073741824  # 1 GiB
    if 'iterations' not in params:
        params['iterations'] = 100  # Default
    if 'warmup_iterations' not in params:
        params['warmup_iterations'] = 5  # Default
    if 'ranks' not in params or params['ranks'] == 0:
        params['ranks'] = 8  # Default
    
    return params


def generate_metadata_for_run(run_dir):
    """Generate metadata for a single run directory."""
    dirname = os.path.basename(run_dir.rstrip('/'))
    
    # Extract info from directory name
    dir_info = extract_metadata_from_dirname(dirname)
    if not dir_info:
        print(f"  ⚠️  Skipping {dirname} - invalid directory name format")
        return False
    
    benchmark = dir_info['benchmark']
    timestamp = dir_info['timestamp']
    
    # Infer parameters from existing files
    params = infer_run_parameters(run_dir, benchmark)
    
    # Build metadata
    metadata = {
        'benchmark': benchmark,
        'ranks': params['ranks'],
        'min_size_bytes': params['min_size_bytes'],
        'max_size_bytes': params['max_size_bytes'],
        'iterations': params['iterations'],
        'warmup_iterations': params['warmup_iterations'],
        'timestamp': timestamp,
        'hostname': socket.gethostname(),
        'output_directory': run_dir,
        'command': f"# Reconstructed from directory analysis",
        'note': 'Metadata regenerated by regenerate_metadata.py'
    }
    
    # Save metadata
    metadata_file = os.path.join(run_dir, 'run_metadata.json')
    with open(metadata_file, 'w') as f:
        json.dump(metadata, f, indent=2)
    
    return True


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Regenerate run_metadata.json files for existing benchmark runs')
    parser.add_argument('--data-dir', default=None,
                       help='Data directory to scan (default: auto-detect from hostname)')
    parser.add_argument('--dry-run', action='store_true',
                       help='Show what would be done without actually creating files')
    
    args = parser.parse_args()
    
    # Determine data directory
    if args.data_dir:
        data_base = args.data_dir
    else:
        hostname = socket.gethostname()
        data_base = f"/work/lmeadows/rccl/data/{hostname}"
    
    if not os.path.exists(data_base):
        print(f"Error: Data directory not found: {data_base}")
        return 1
    
    print(f"Scanning for run directories in: {data_base}")
    print("="*80)
    
    # Find all run directories
    run_dirs = glob.glob(os.path.join(data_base, 'run_*_202*'))
    run_dirs = [d for d in run_dirs if os.path.isdir(d)]
    run_dirs.sort()
    
    if not run_dirs:
        print("No run directories found")
        return 0
    
    print(f"Found {len(run_dirs)} run directories")
    print()
    
    success_count = 0
    skip_count = 0
    
    for run_dir in run_dirs:
        dirname = os.path.basename(run_dir)
        metadata_file = os.path.join(run_dir, 'run_metadata.json')
        
        # Check if metadata already exists
        if os.path.exists(metadata_file):
            print(f"  ✓ {dirname} - metadata exists")
            skip_count += 1
            continue
        
        if args.dry_run:
            print(f"  🔍 {dirname} - would create metadata")
            success_count += 1
        else:
            print(f"  ➕ {dirname} - creating metadata")
            if generate_metadata_for_run(run_dir):
                success_count += 1
            else:
                skip_count += 1
    
    print()
    print("="*80)
    print(f"Summary:")
    print(f"  Created: {success_count}")
    print(f"  Skipped: {skip_count}")
    print(f"  Total: {len(run_dirs)}")
    print("="*80)
    
    return 0


if __name__ == '__main__':
    sys.exit(main())

